spring.application.name=project-management-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/pmt
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=true


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN

jwt.secret=YOUR_BASE64_SECRET_KEY
jwt.expiration=86400000